package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 17:24:47 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(name="ACTIONS"
    ,catalog="trauth"
)
public class Actions  implements java.io.Serializable {


     private String name;
     private Set<Permissions> permissionses = new HashSet<Permissions>(0);

    public Actions() {
    }

	
    public Actions(String name) {
        this.name = name;
    }
    public Actions(String name, Set<Permissions> permissionses) {
       this.name = name;
       this.permissionses = permissionses;
    }
   
     @Id 
    
    @Column(name="NAME", unique=true, nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="actions")
    public Set<Permissions> getPermissionses() {
        return this.permissionses;
    }
    
    public void setPermissionses(Set<Permissions> permissionses) {
        this.permissionses = permissionses;
    }




}


