package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 17:24:47 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name="PERMISSIONS"
    ,catalog="trauth"
)
public class Permissions  implements java.io.Serializable {


     private PermissionsId id;
     private Actions actions;
     private Resourcegroups resourcegroups;
     private Roles roles;

    public Permissions() {
    }

	
    public Permissions(PermissionsId id, Actions actions, Roles roles) {
        this.id = id;
        this.actions = actions;
        this.roles = roles;
    }
    public Permissions(PermissionsId id, Actions actions, Resourcegroups resourcegroups, Roles roles) {
       this.id = id;
       this.actions = actions;
       this.resourcegroups = resourcegroups;
       this.roles = roles;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="roleName", column=@Column(name="ROLE_NAME", nullable=false, length=150) ), 
        @AttributeOverride(name="actionName", column=@Column(name="ACTION_NAME", nullable=false, length=30) ), 
        @AttributeOverride(name="resourcegroupName", column=@Column(name="RESOURCEGROUP_NAME", length=40) ) } )
    public PermissionsId getId() {
        return this.id;
    }
    
    public void setId(PermissionsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTION_NAME", nullable=false, insertable=false, updatable=false)
    public Actions getActions() {
        return this.actions;
    }
    
    public void setActions(Actions actions) {
        this.actions = actions;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCEGROUP_NAME", insertable=false, updatable=false)
    public Resourcegroups getResourcegroups() {
        return this.resourcegroups;
    }
    
    public void setResourcegroups(Resourcegroups resourcegroups) {
        this.resourcegroups = resourcegroups;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_NAME", nullable=false, insertable=false, updatable=false)
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }




}


