package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 17:24:47 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="ROLES"
    ,catalog="trauth"
)
public class Roles  implements java.io.Serializable {


     private String name;
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<Permissions> permissionses = new HashSet<Permissions>(0);

    public Roles() {
    }

	
    public Roles(String name) {
        this.name = name;
    }
    public Roles(String name, Set<Users> userses, Set<Permissions> permissionses) {
       this.name = name;
       this.userses = userses;
       this.permissionses = permissionses;
    }
   
     @Id 
    
    @Column(name="NAME", unique=true, nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="USERS_ROLES", catalog="trauth", joinColumns = { 
        @JoinColumn(name="ROLE_NAME", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="USER_NAME", nullable=false, updatable=false) })
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="roles")
    public Set<Permissions> getPermissionses() {
        return this.permissionses;
    }
    
    public void setPermissionses(Set<Permissions> permissionses) {
        this.permissionses = permissionses;
    }




}


