package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 17:24:47 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UrnResourcegroups generated by hbm2java
 */
@Entity
@Table(name="URN_RESOURCEGROUPS"
    ,catalog="trauth"
)
public class UrnResourcegroups  implements java.io.Serializable {


     private UrnResourcegroupsId id;
     private Resourcegroups resourcegroups;

    public UrnResourcegroups() {
    }

    public UrnResourcegroups(UrnResourcegroupsId id, Resourcegroups resourcegroups) {
       this.id = id;
       this.resourcegroups = resourcegroups;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="urn", column=@Column(name="URN", nullable=false) ), 
        @AttributeOverride(name="resourcegroup", column=@Column(name="RESOURCEGROUP", nullable=false, length=40) ) } )
    public UrnResourcegroupsId getId() {
        return this.id;
    }
    
    public void setId(UrnResourcegroupsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCEGROUP", nullable=false, insertable=false, updatable=false)
    public Resourcegroups getResourcegroups() {
        return this.resourcegroups;
    }
    
    public void setResourcegroups(Resourcegroups resourcegroups) {
        this.resourcegroups = resourcegroups;
    }




}


