package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 16:12:41 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesId generated by hbm2java
 */
@Embeddable
public class UsersRolesId  implements java.io.Serializable {


     private String roleName;
     private String userName;

    public UsersRolesId() {
    }

    public UsersRolesId(String roleName, String userName) {
       this.roleName = roleName;
       this.userName = userName;
    }
   

    @Column(name="ROLE_NAME", nullable=false, length=150)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name="USER_NAME", nullable=false, length=150)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersRolesId) ) return false;
		 UsersRolesId castOther = ( UsersRolesId ) other; 
         
		 return ( (this.getRoleName()==castOther.getRoleName()) || ( this.getRoleName()!=null && castOther.getRoleName()!=null && this.getRoleName().equals(castOther.getRoleName()) ) )
 && ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRoleName() == null ? 0 : this.getRoleName().hashCode() );
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         return result;
   }   


}


