package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 28.08.2012 16:12:41 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name="USERS_ROLES"
    ,catalog="trauth"
)
public class UsersRoles  implements java.io.Serializable {


     private UsersRolesId id;

    public UsersRoles() {
    }

    public UsersRoles(UsersRolesId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="roleName", column=@Column(name="ROLE_NAME", nullable=false, length=150) ), 
        @AttributeOverride(name="userName", column=@Column(name="USER_NAME", nullable=false, length=150) ) } )
    public UsersRolesId getId() {
        return this.id;
    }
    
    public void setId(UsersRolesId id) {
        this.id = id;
    }




}


